---
name: Bug 报告
description: 提交 Sky Canvas 的问题或缺陷
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的反馈！请尽可能完整地填写以下信息，帮助我们快速定位问题。
  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: 预检查
      options:
        - label: 我已阅读 [Code of Conduct](/CODE_OF_CONDUCT.md)
          required: true
        - label: 我已搜索过已有 Issue，确认不是重复问题
          required: true
  - type: dropdown
    id: scope
    attributes:
      label: 影响范围
      options:
        - render-engine
        - canvas-sdk
        - root app
        - docs
        - 其他
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 简洁描述问题现象
      placeholder: 例如：使用某 API 时出现崩溃/渲染异常
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: 复现步骤
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 期望行为
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 实际行为
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: 环境信息
      placeholder: |
        OS:
        Node.js:
        pnpm:
        浏览器:
  - type: textarea
    id: logs
    attributes:
      label: 日志或截图
      description: 如有，请提供相关日志、报错或截图
