---
name: 功能建议
description: 提出新功能或改进建议
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你的建议！请提供尽可能完整的信息，帮助我们评估需求。
  - type: checkboxes
    id: preliminary-checks
    attributes:
      label: 预检查
      options:
        - label: 我已阅读 [Code of Conduct](/CODE_OF_CONDUCT.md)
          required: true
        - label: 我已搜索过已有 Issue，确认不是重复建议
          required: true
  - type: dropdown
    id: scope
    attributes:
      label: 目标模块
      options:
        - render-engine
        - canvas-sdk
        - root app
        - docs
        - 其他
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: 需求背景
      description: 目前遇到什么问题或限制？
      placeholder: 例如：需要支持新的渲染能力或更好的扩展方式
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 期望方案
      description: 你希望我们如何实现？
      placeholder: 例如：新增 API / 示例 / 配置选项
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 可替代方案
      description: 是否考虑过其他方案或 workaround？
  - type: textarea
    id: additional
    attributes:
      label: 补充信息
      description: 任何额外信息、参考链接或截图
